server.port: 8081

logging:
  level:
    root: WARN
    demo.use.starters: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
        errorDecoder: demo.use.starters.client.handler.ClientErrorDecoder

drink:
    url: http://localhost:8080
    name:
      azure-application-id-scope: some-uuid-scope/.default

# Kong oauth2 properties
azure:
  security:
    oauth:
      # note - tokenUrl is used for defining the "aud" part of the Jwt claimset.  It is NOT the url that we call to get the token
      tokenUrl: https://login.microsoftonline.com/6e93a626-8aca-4dc1-9191-ce291b4b75a1/oauth2/v2.0/token
      clientId: some-uuid-clientid
      certificateAlias: cert
      keystoreFileResource: classpath:your-jks.jks
      keystorePassword: your-keystore-password-from-secured-place

