openapi: 3.0.2
info:
  title: "Drink service"
  description: "Allows consumers of the API to create a drink"
  version: 1.0.0
servers:
  - url: dummy
    description: "Test url"

tags:
  - name: drink
    description: "Drink controller"
paths:
  /drinks/{drink}:
    post:
      tags:
        - drink
      operationId: createDrink
      parameters:
        - name: drink
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved search results
          content:
            application/json:
              schema:
                $ref: './schemas/CreatedDrink.yml'
        400:
          description: "Bad request"
        500:
          description: "Server error"
